### ISSUE TITLE
Redo other StatTooltipData sections

### ISSUE THREAD

**Issue by CptMoore** [BattletechModders/MechEngineer#175]
[emod_armorslots_impactresistant.json.txt](https://github.com/BattletechModders/MechEngineer/files/4112317/emod_armorslots_impactresistant.json.txt)
[Gear_Spall_Liner_Upgrade.json.txt](https://github.com/BattletechModders/MechEngineer/files/4112318/Gear_Spall_Liner_Upgrade.json.txt)
[emod_arm_part_hand.json.txt](https://github.com/BattletechModders/MechEngineer/files/4112273/emod_arm_part_hand.json.txt)
[Gear_HeatSink_Generic_Bulk-Bank.json.txt](https://github.com/BattletechModders/MechEngineer/files/4112274/Gear_HeatSink_Generic_Bulk-Bank.json.txt)
[WeaponCategory.json.txt](https://github.com/BattletechModders/MechEngineer/files/4112240/WeaponCategory.json.txt)

already redone are:
- movement
- heat

remove melee, range and firepower and replace with:
- close combat (include melee and small/support weapon stats, see ladys comment regarding split)
- medium range firepower (> melee && < large laser)
- long range firepower (has extreme long range as special stat for erlarge and erppc)
for each:
- damage
- heat / stability damage
- accuracy
- range

That leaves open:
- durability, which should be structure + armor including all armor/structure mods and status effect changes, add defense!! and tohitthisactor DamageReductionMultiplierAll

**Comment by LadyAlekto** [comment]
Heat needs to account for Int_Multiply_Float and would it be possible you can work with frosty to have a cbtbe flag for that so me shows that heat scale?

Also Melee damage should look for chassisdef melee damage as base, not assume vanillas base damage and apply a -quirk when its less then tonnage

Another thing as i said in discord, i wouldnt include support/small weapons in close combat, but look if a category has "CanUseInMelee" : true, in its enum

**Comment by LadyAlekto** [comment]
Other stats not Correctly shown

HeatSinkCapacity since it calculates from 0 not from total (eg in_mutliply_float heatsinkcapacity 1.2 results in zero, not total*1,2 )

A good breakdown would be

Base Capacity+Multipliers
Total Weapon heat reduction (either a total, or a breakdown of by category/weapontype)
And show the final total "alpha strike heat" of Heatgenerated/Heatreduction (this does vanilla correct already)-Capacity

For melee

Base Melee Damage = chassisdefs
quirks changed to "Melee modifiers" (all float_adds + *float_multiply)
and the last "all together" Base Damage+total modifiers

For defense

Knowing all damage reduction multipliers like DamageReductionMultiplierBallistic and ToHitThisActor

**Comment by CptMoore** [comment]
For defense I only use DamageReductionMultiplierAll and none of the others.
For ToHitThisActor the same, only the general one, none of the specific ones.

6 main stats
each can have 6 substats
and each substat can contain up to 3 parts (depending on space)
Just couldn't fit everything in.

I don't know what was meant "Base Capacity" in the previous comment, sry.

Other than that I'm finished, just reopen or so if something is amiss.
