### ISSUE TITLE
DynamicSlots Moveable slots has no UIName

### ISSUE THREAD

**Issue by iAcolyte** [BattletechModders/MechEngineer#203]
When I try to install some module then use dynamics slots, the slots don't show UIName, so you can see only the movable slot label.

![изображение](https://user-images.githubusercontent.com/53187739/122126693-c7c60300-ce3a-11eb-9a6d-9b97b5080d72.png)

I fixed it by adding NameText in JSON

```json
"DynamicSlots": {
    "NameText" : "Ferro-Fibrous",
    "ReservedSlots": 14
},
```

**Comment by CptMoore** [comment]
Thats intentional! Movable/fixed slots are just slots that take up space and shouldn't clutter the UI with unnecessary text. Colors are used to know which component the space is used up by.

RogueTech and I think BTA both use UIName or more precisely they say "NameText": null
```
        public string NameText { get; set; } = ""; // null: use component name
        public string BonusAText { get; set; } = ""; // null: use component bonus, "": dont show
        public string BonusBText { get; set; } = ""; // null: use component bonus, "": dont show
        public string BackgroundColor { get; set; } = null; // null: use component color
```

If you need it, I could probably introduce a global default that is used by components, so as to make it easier for you to change all dynamic slots to your preferred style.

**Comment by iAcolyte** [comment]
I use the mod without RogueTech. And I saw the names there, so I thought it is a problem. 

Maybe use some JSON settings is a good decision. Or add some Readme information. 

Anyway, thank you for your reply, awesome mod!
